apiVersion: config.polyglot.systems/v1
kind: KeystoreSentinel
metadata:
  name: keystoresentinel-sample-secrets-logger
  namespace: cert-sentinel
spec:
  alert:
    config:
      reportInterval: debug
    name: secrets-logger
    type: logger
  target:
    apiVersion: v1
    daysOut:
      - 30
      - 60
      - 90
      - 9001
      - 9000
    kind: Secret
    name: all-secrets-logger
    namespaces:
      - "*"
    serviceAccount: some-service-account
    keystorePassword:
      plaintext: password123
      type: plaintext

      #type: labels
      #labelRef:
      #  key: keystore-pass
      #  labelSelectors:
      #    - key: polyglot.systems/asset
      #      value:
      #      - keystore-password
      
      #type: secret
      #secretRef:
      #  key: keystore-pass
      #  name: keystore-secret-password
    namespaceLabels:
      - key: polyglot.systems/keystore-sentinel-namespace
        value:
          - 'true'
  logLevel: 3