apiVersion: config.polyglot.systems/v1
kind: KeystoreSentinel
metadata:
  name: keystoresentinel-sample-secrets-mailer
  namespace: cert-sentinel
spec:
  alert:
    name: secrets-mailer
    type: smtp
    config:
      reportInterval: debug
      smtp_auth_secret: my-gmail-smtp-secret
      smtp_auth_type: plain
      smtp_destination_addresses:
        - ken@kenmoini.com
        - ken.moini@gmail.com
      smtp_endpoint: 'smtp.gmail.com:587'
      smtp_sender_hostname: core-ocp.kemo.labs
      smtp_use_ssl: true
      smtp_use_starttls: true
  target:
    apiVersion: v1
    daysOut:
      - 30
      - 60
      - 90
      - 9001
      - 9000
    kind: Secret
    name: all-secrets-mailer
    namespaces:
      - "*"
    serviceAccount: some-service-account
    keystorePassword:
      plaintext: password123
      type: plaintext

      #type: labels
      #labelRef:
      #  key: keystore-pass
      #  labelSelectors:
      #    - key: polyglot.systems/asset
      #      value:
      #      - keystore-password
      
      #type: secret
      #secretRef:
      #  key: keystore-pass
      #  name: keystore-secret-password
    namespaceLabels:
      - key: polyglot.systems/keystore-sentinel-namespace
        value:
          - 'true'
  logLevel: 3