apiVersion: config.polyglot.systems/v1
kind: CertificateSentinel
metadata:
  name: certificatesentinel-sample-secrets-logger
  namespace: cert-sentinel
spec:
  alert:
    config:
      reportInterval: debug
    name: secrets-logger
    type: logger
  target:
    apiVersion: v1
    daysOut:
      - 30
      - 60
      - 90
      - 9001
      - 9000
    kind: Secret
    name: all-secrets-logger
    namespaces:
      - "*"
    serviceAccount: some-service-account