//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 Polyglot Systems.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Alert) DeepCopyInto(out *Alert) {
	*out = *in
	in.AlertConfiguration.DeepCopyInto(&out.AlertConfiguration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Alert.
func (in *Alert) DeepCopy() *Alert {
	if in == nil {
		return nil
	}
	out := new(Alert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertConfiguration) DeepCopyInto(out *AlertConfiguration) {
	*out = *in
	if in.SMTPDestinationEmailAddresses != nil {
		in, out := &in.SMTPDestinationEmailAddresses, &out.SMTPDestinationEmailAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SMTPAuthUseSSL != nil {
		in, out := &in.SMTPAuthUseSSL, &out.SMTPAuthUseSSL
		*out = new(bool)
		**out = **in
	}
	if in.SMTPAuthUseSTARTTLS != nil {
		in, out := &in.SMTPAuthUseSTARTTLS, &out.SMTPAuthUseSTARTTLS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertConfiguration.
func (in *AlertConfiguration) DeepCopy() *AlertConfiguration {
	if in == nil {
		return nil
	}
	out := new(AlertConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateInformation) DeepCopyInto(out *CertificateInformation) {
	*out = *in
	if in.TriggeredDaysOut != nil {
		in, out := &in.TriggeredDaysOut, &out.TriggeredDaysOut
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateInformation.
func (in *CertificateInformation) DeepCopy() *CertificateInformation {
	if in == nil {
		return nil
	}
	out := new(CertificateInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSentinel) DeepCopyInto(out *CertificateSentinel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSentinel.
func (in *CertificateSentinel) DeepCopy() *CertificateSentinel {
	if in == nil {
		return nil
	}
	out := new(CertificateSentinel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateSentinel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSentinelList) DeepCopyInto(out *CertificateSentinelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertificateSentinel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSentinelList.
func (in *CertificateSentinelList) DeepCopy() *CertificateSentinelList {
	if in == nil {
		return nil
	}
	out := new(CertificateSentinelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateSentinelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSentinelSpec) DeepCopyInto(out *CertificateSentinelSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	in.Alert.DeepCopyInto(&out.Alert)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSentinelSpec.
func (in *CertificateSentinelSpec) DeepCopy() *CertificateSentinelSpec {
	if in == nil {
		return nil
	}
	out := new(CertificateSentinelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSentinelStatus) DeepCopyInto(out *CertificateSentinelStatus) {
	*out = *in
	if in.DiscoveredCertificates != nil {
		in, out := &in.DiscoveredCertificates, &out.DiscoveredCertificates
		*out = make([]CertificateInformation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSentinelStatus.
func (in *CertificateSentinelStatus) DeepCopy() *CertificateSentinelStatus {
	if in == nil {
		return nil
	}
	out := new(CertificateSentinelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoreInformation) DeepCopyInto(out *KeystoreInformation) {
	*out = *in
	if in.TriggeredDaysOut != nil {
		in, out := &in.TriggeredDaysOut, &out.TriggeredDaysOut
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoreInformation.
func (in *KeystoreInformation) DeepCopy() *KeystoreInformation {
	if in == nil {
		return nil
	}
	out := new(KeystoreInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystorePassword) DeepCopyInto(out *KeystorePassword) {
	*out = *in
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Secret = in.Secret
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystorePassword.
func (in *KeystorePassword) DeepCopy() *KeystorePassword {
	if in == nil {
		return nil
	}
	out := new(KeystorePassword)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoreSentinel) DeepCopyInto(out *KeystoreSentinel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoreSentinel.
func (in *KeystoreSentinel) DeepCopy() *KeystoreSentinel {
	if in == nil {
		return nil
	}
	out := new(KeystoreSentinel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeystoreSentinel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoreSentinelList) DeepCopyInto(out *KeystoreSentinelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeystoreSentinel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoreSentinelList.
func (in *KeystoreSentinelList) DeepCopy() *KeystoreSentinelList {
	if in == nil {
		return nil
	}
	out := new(KeystoreSentinelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeystoreSentinelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoreSentinelSpec) DeepCopyInto(out *KeystoreSentinelSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	in.Alert.DeepCopyInto(&out.Alert)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoreSentinelSpec.
func (in *KeystoreSentinelSpec) DeepCopy() *KeystoreSentinelSpec {
	if in == nil {
		return nil
	}
	out := new(KeystoreSentinelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoreSentinelStatus) DeepCopyInto(out *KeystoreSentinelStatus) {
	*out = *in
	if in.DiscoveredKeystores != nil {
		in, out := &in.DiscoveredKeystores, &out.DiscoveredKeystores
		*out = make([]KeystoreInformation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoreSentinelStatus.
func (in *KeystoreSentinelStatus) DeepCopy() *KeystoreSentinelStatus {
	if in == nil {
		return nil
	}
	out := new(KeystoreSentinelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoreTarget) DeepCopyInto(out *KeystoreTarget) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceLabels != nil {
		in, out := &in.NamespaceLabels, &out.NamespaceLabels
		*out = make([]LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetLabels != nil {
		in, out := &in.TargetLabels, &out.TargetLabels
		*out = make([]LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DaysOut != nil {
		in, out := &in.DaysOut, &out.DaysOut
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	in.KeystorePassword.DeepCopyInto(&out.KeystorePassword)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeystoreTarget.
func (in *KeystoreTarget) DeepCopy() *KeystoreTarget {
	if in == nil {
		return nil
	}
	out := new(KeystoreTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelSelector) DeepCopyInto(out *LabelSelector) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelSelector.
func (in *LabelSelector) DeepCopy() *LabelSelector {
	if in == nil {
		return nil
	}
	out := new(LabelSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceLabels != nil {
		in, out := &in.NamespaceLabels, &out.NamespaceLabels
		*out = make([]LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetLabels != nil {
		in, out := &in.TargetLabels, &out.TargetLabels
		*out = make([]LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DaysOut != nil {
		in, out := &in.DaysOut, &out.DaysOut
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Target.
func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlice) DeepCopyInto(out *TimeSlice) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlice.
func (in *TimeSlice) DeepCopy() *TimeSlice {
	if in == nil {
		return nil
	}
	out := new(TimeSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in TimeSlices) DeepCopyInto(out *TimeSlices) {
	{
		in := &in
		*out = make(TimeSlices, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlices.
func (in TimeSlices) DeepCopy() TimeSlices {
	if in == nil {
		return nil
	}
	out := new(TimeSlices)
	in.DeepCopyInto(out)
	return *out
}
